### ISSUE TITLE
ERROR DURING MOD LOADING

### ISSUE THREAD

**Issue by BugrahanTelli** [KitKait2001/roamers#10]
[crash-2024-10-16_17.32.06-fml.txt](https://github.com/user-attachments/files/17397468/crash-2024-10-16_17.32.06-fml.txt)

I had an error that says roamers has failed to load correctly.

 java.lang.ExceptionInInitializerError : null   
 

 (Roamers v.2.1  Forge 1.21.1)

**Comment by KitKait2001** [comment]
Thanks for the crash log! I find it interesting because this was never an issue before now, and even upon testing outside of the Dev environment and in a modpack. 

Basically, the Config is getting my specific mod's Logger before it is created, so there might be a compatibility issue with other modding libraries that delay the logger from being initialized, or something else I don't know about. Completely on my end though!

I am releasing a patch release to fix this today, after more testing of course! It's a simple fix lol just moving the config initialization to the Common Setup Event.  This should prevent the crash from happening and make it more compatible. Thanks for this, and sorry about the crash! :)

**Comment by BugrahanTelli** [comment]
TYSM, Love this mod. HAVE A GREAT DAY <3

**Comment by KitKait2001** [comment]
The hotfix is updated, if you have any more issues feel free to reopen this issue or DM me on discord for any help! :)
